---
- name: Lab 4 - Loops and Linux Patching
  hosts: workers
  become: true

  vars_files:
    - vars.yml

  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade installed packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Install common packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: "{{package_state }}"
      loop: "{{ packages }}"

    - name: Remove unnecessary packages
      ansible.builtin.apt:
        autoremove: true

    - name: Ensure Docker service is enabled and running
      ansible.builtin.service:
        name: "{{ docker_service_name }}"
        state: "{{ docker_service_state }}"
        enabled: "{{ docker_service_enabled }}"
